import {test} from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync} from 'node:fs';import worker,{digest,token,cookieNames} from '../src/worker.js';
function database() {
 const db=new DatabaseSync(':memory:'); db.exec(readFileSync(new URL('../schema.sql',import.meta.url),'utf8'));
 function statement(sql,args=[]) { return {bind(...values){return statement(sql,values);},async first(){return db.prepare(sql).get(...args)||null;},async all(){return {results:db.prepare(sql).all(...args)};},async run(){return db.prepare(sql).run(...args);}}; }
 return {prepare:statement,async batch(items){db.exec('BEGIN');try{const r=await Promise.all(items.map(s=>s.run()));db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}}};
}
async function fixture(){const bootstrap=token();const env={DB:database(),ANSWER_DIGEST:await digest('2025-01-02'),BOOTSTRAP_DIGEST:await digest(bootstrap),DATA_KEY:btoa(String.fromCharCode(...crypto.getRandomValues(new Uint8Array(32))))};let cookie='';return {env,bootstrap,setCookie(v){cookie=v;},cookie(){return cookie;},async req(path,v,options={}){const request=new Request('https://example.com/api/'+path,{method:v===undefined?'GET':'POST',headers:{Cookie:options.cookie??cookie,...(v===undefined?{}:{Origin:'https://example.com','Content-Type':'application/json'}),'CF-Connecting-IP':options.ip||'127.0.0.1'},body:v===undefined?undefined:JSON.stringify(v)});const response=await worker.fetch(request,env);for(const c of response.headers.getSetCookie()){const pair=c.split(';')[0],name=pair.split('=')[0];const parts=cookie.split('; ').filter(p=>p&&!p.startsWith(name+'='));parts.push(pair);cookie=parts.join('; ');}return {status:response.status,body:await response.json(),response};}};}
test('correct date alone never authorizes a new device; bootstrap is one use',async()=>{const f=await fixture();assert.equal((await f.req('unlock',{answer:'2025-01-02'})).status,401);const a=await f.req('unlock',{answer:'2025-01-02',invitation:f.bootstrap});assert.equal(a.status,200);for(const c of a.response.headers.getSetCookie()){assert.match(c,/Secure; HttpOnly; SameSite=Strict/);}assert.equal((await f.req('entries')).status,200);f.setCookie('');assert.equal((await f.req('unlock',{answer:'2025-01-02',invitation:f.bootstrap})).status,401);});
test('CRUD is encrypted at rest and lock invalidates an old session',async()=>{const f=await fixture();await f.req('unlock',{answer:'2025-01-02',invitation:f.bootstrap});const old=f.cookie();assert.equal((await f.req('entries',{start:'2025-02-01',end:'2025-02-05',note:'fixture only'})).status,200);const rows=await f.env.DB.prepare('SELECT * FROM entries').bind().all();assert.ok(!JSON.stringify(rows).includes('fixture only'));let list=await f.req('entries');const id=list.body.entries[0].id;assert.equal(list.body.entries[0].note,'fixture only');await f.req('entries',{id,start:'2025-02-01',end:'2025-02-06',note:'edited'});assert.equal((await f.req('entries')).body.entries[0].note,'edited');await f.req('delete',{id});assert.deepEqual((await f.req('entries')).body.entries,[]);await f.req('lock',{});assert.equal((await f.req('entries',undefined,{cookie:old})).status,401);assert.equal((await f.req('unlock',{answer:'2025-01-02'})).status,200);});
test('invite expires, is single use and revoked devices lose all sessions',async()=>{const f=await fixture();await f.req('unlock',{answer:'2025-01-02',invitation:f.bootstrap});const owner=f.cookie();const invitation=(await f.req('invite',{})).body.code;f.setCookie('');assert.equal((await f.req('unlock',{answer:'2025-01-02',invitation})).status,200);const guest=f.cookie();const guestHash=await digest(guest.split('; ').find(p=>p.startsWith(cookieNames.device+'=')).split('=')[1]);f.setCookie('');assert.equal((await f.req('unlock',{answer:'2025-01-02',invitation})).status,401);f.setCookie(owner);await f.req('revoke',{hash:guestHash});assert.equal((await f.req('entries',undefined,{cookie:guest})).status,401);const expired=token();await f.env.DB.prepare('INSERT INTO invitations(hash,expires) VALUES (?,?)').bind(await digest(expired),0).run();f.setCookie('');assert.equal((await f.req('unlock',{answer:'2025-01-02',invitation:expired})).status,401);});
test('expired and idle sessions cannot read records',async()=>{const f=await fixture();await f.req('unlock',{answer:'2025-01-02',invitation:f.bootstrap});await f.env.DB.prepare('UPDATE sessions SET seen=0').bind().run();assert.equal((await f.req('entries')).status,401);await f.req('unlock',{answer:'2025-01-02'});await f.env.DB.prepare('UPDATE sessions SET expires=0').bind().run();assert.equal((await f.req('entries')).status,401);});
test('brute-force attempts are limited even when the answer becomes correct',async()=>{const f=await fixture();for(let i=0;i<10;i++)assert.equal((await f.req('unlock',{answer:'2025-01-03'})).status,401);assert.equal((await f.req('unlock',{answer:'2025-01-02',invitation:f.bootstrap})).status,429);});

test('only an unlocked device can stop this round, and the stop marker contains no plain date',async()=>{const f=await fixture();assert.equal((await f.req('pause-reminders',{})).status,401);await f.req('unlock',{answer:'2025-01-02',invitation:f.bootstrap});assert.equal((await f.req('pause-reminders',{})).status,400);await f.req('entries',{start:'2025-02-01',end:'',note:''});assert.equal((await f.req('pause-reminders',{})).status,200);const row=await f.env.DB.prepare("SELECT value FROM reminder_state WHERE key='paused'").first();assert.equal(row.value,await digest('2025-02-01'));});
