import {test} from 'node:test';import assert from 'node:assert/strict';import {createHmac} from 'node:crypto';import {readFileSync} from 'node:fs';import {runInNewContext} from 'node:vm';import {DatabaseSync} from 'node:sqlite';import {prediction,sendReminder,seal} from '../src/worker.js';
const dates=['2025-01-01','2025-01-28','2025-02-21','2025-03-20','2025-04-15'];
test('range uses recent distinct start dates and pauses unusual or insufficient history',()=>{const entries=dates.map(start=>({start}));assert.deepEqual(prediction(entries,'2025-05-01'),{latest:'2025-04-15',from:'2025-05-09',to:'2025-05-12',advance:'2025-05-07'});assert.equal(prediction(entries.slice(0,2),'2025-05-01'),null);assert.equal(prediction([...entries,{start:'2025-04-20'}],'2025-05-01'),null);assert.deepEqual(prediction([...entries,{start:'2025-12-01'},entries[0]],'2025-05-01'),prediction(entries,'2025-05-01'));});
async function fixture(){const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE entries(sealed TEXT,updated INTEGER)');const DB={prepare(sql){let args=[];return {bind(...a){args=a;return this;},async run(){return db.prepare(sql).run(...args);},async first(){return db.prepare(sql).get(...args);},async all(){return {results:db.prepare(sql).all(...args)};}};}};const env={DB,DATA_KEY:Buffer.alloc(32,2).toString('base64'),MAIL_ENABLED:'true',MAIL_RELAY_URL:'https://script.google.com/macros/s/example/exec',MAIL_RELAY_KEY:'a'.repeat(64)};for(const start of dates)db.prepare('INSERT INTO entries VALUES (?,0)').run(await seal({start,end:'',note:'private note'},env.DATA_KEY));return {db,env};}
test('scheduled sends only in window, signed without private dates, once per day; pause suppresses mail',async()=>{const {db,env}=await fixture();let count=0;const send=async(url,opts)=>{count++;const v=JSON.parse(opts.body);assert.equal(v.signature,createHmac('sha256',env.MAIL_RELAY_KEY).update(v.day+'|'+v.timestamp).digest('hex'));assert.ok(!opts.body.includes('private note'));assert.ok(!opts.body.includes('2025-04-15'));return Response.json({ok:true});};await sendReminder(env,Date.parse('2025-05-06T01:00Z'),send);assert.equal(count,0);await sendReminder(env,Date.parse('2025-05-07T01:00Z'),send);await sendReminder(env,Date.parse('2025-05-07T02:00Z'),send);assert.equal(count,1);const {digest}=await import('../src/worker.js');db.prepare("INSERT INTO reminder_state VALUES ('paused',?)").run(await digest('2025-04-15'));await sendReminder(env,Date.parse('2025-05-08T01:00Z'),send);assert.equal(count,1);});
test('relay errors get at most three attempts and sending disabled never contacts relay',async()=>{const {env}=await fixture();let count=0;const send=async()=>{count++;throw Error('network');};for(let i=0;i<5;i++)await sendReminder(env,Date.parse('2025-05-07T01:00Z'),send).catch(()=>{});assert.equal(count,3);env.MAIL_ENABLED='false';await sendReminder(env,Date.parse('2025-05-08T01:00Z'),send);assert.equal(count,3);});
function relay(){const values=new Map([['MAIL_RELAY_KEY','a'.repeat(64)]]),sent=[];const props={getProperty:k=>values.get(k),setProperty:(k,v)=>values.set(k,v),deleteProperty:k=>values.delete(k)};const sandbox={PropertiesService:{getScriptProperties:()=>props},Utilities:{Charset:{UTF_8:0},formatDate:()=>new Date(Date.now()+8*3600000).toISOString().slice(0,10),computeHmacSha256Signature:(v,k)=>[...createHmac('sha256',k).update(v).digest()]},LockService:{getScriptLock:()=>({tryLock:()=>true,releaseLock(){}})},MailApp:{getRemainingDailyQuota:()=>10,sendEmail:v=>sent.push(v)},ContentService:{MimeType:{JSON:0},createTextOutput:v=>({setMimeType:()=>JSON.parse(v)})}};runInNewContext(readFileSync(new URL('../mail-relay.gs',import.meta.url),'utf8'),sandbox);const day=sandbox.Utilities.formatDate(),timestamp=Date.now(),signature=createHmac('sha256','a'.repeat(64)).update(day+'|'+timestamp).digest('hex');return {sandbox,sent,values,v:{day,timestamp,signature},post(v){return sandbox.doPost({postData:{contents:JSON.stringify(v)}});}};}
test('Google relay rejects bad signatures, old requests and arbitrary recipient; valid requests deduplicate',()=>{const r=relay();assert.equal(r.post({...r.v,signature:'0'.repeat(64)}).ok,false);assert.equal(r.post({...r.v,timestamp:0}).ok,false);assert.equal(r.sent.length,0);assert.equal(r.post({...r.v,to:'attacker@example.com',body:'arbitrary'}).ok,true);assert.equal(r.sent[0].to,'838707379@qq.com');assert.ok(!r.sent[0].body.includes('arbitrary'));assert.equal(r.post(r.v).ok,true);assert.equal(r.sent.length,1);});
test('uncertain Google sends are not retried and missing keys fail closed',()=>{const r=relay();r.sandbox.MailApp.sendEmail=()=>{throw Error('unknown delivery');};assert.equal(r.post(r.v).ok,false);assert.equal(r.post(r.v).uncertain,true);r.values.delete('MAIL_RELAY_KEY');assert.equal(r.post(r.v).ok,false);});
