import {test} from 'node:test';import assert from 'node:assert/strict';
import worker,{validDate,validEntry,digest,seal,unseal,cookieNames} from '../src/worker.js';
test('reject invalid calendar dates and inconsistent period ranges',()=>{assert.ok(validDate('2025-02-28'));assert.equal(validDate('2025-02-29'),false);assert.equal(validDate('2025-13-01'),false);assert.equal(validEntry({start:'2025-03-01',end:'2025-02-28',note:''}),false);assert.equal(validEntry({start:'2025-03-01',note:'x'.repeat(501)}),false);});
test('stored record is encrypted, randomized and authenticated',async()=>{const key=btoa(String.fromCharCode(...crypto.getRandomValues(new Uint8Array(32))));const v={start:'2025-03-01',end:'',note:'private note'};const a=await seal(v,key),b=await seal(v,key);assert.notEqual(a,b);assert.ok(!a.includes(v.note));assert.deepEqual(await unseal(a,key),v);const bytes=Uint8Array.from(atob(a),c=>c.charCodeAt(0));bytes[15]^=1;await assert.rejects(unseal(btoa(String.fromCharCode(...bytes)),key));});
const env={ANSWER_DIGEST:'configured',DATA_KEY:'configured',BOOTSTRAP_DIGEST:'configured',DB:{prepare(){throw Error('unexpected database access');}}};
test('unauthenticated callers cannot list, write, delete or invite',async()=>{for(const [path,method] of [['entries','GET'],['entries','POST'],['delete','POST'],['invite','POST'],['devices','GET'],['revoke','POST']]){const r=await worker.fetch(new Request('https://example.com/api/'+path,{method,headers:method==='POST'?{'Origin':'https://example.com','Content-Type':'application/json'}:{},body:method==='POST'?'{}':undefined}),env);assert.equal(r.status,401);assert.equal(r.headers.get('Cache-Control'),'no-store');}});
test('cross origin and form posts are rejected before database access',async()=>{for(const h of [{'Origin':'https://evil.example','Content-Type':'application/json'},{'Origin':'https://example.com','Content-Type':'application/x-www-form-urlencoded'},{}]){const r=await worker.fetch(new Request('https://example.com/api/unlock',{method:'POST',headers:h,body:'{}'}),env);assert.equal(r.status,403);}});
test('unconfigured deployment fails closed',async()=>{assert.equal((await worker.fetch(new Request('https://example.com/api/entries'),{})).status,503);});
test('tokens use host-only secure cookie names and hashes are deterministic',async()=>{assert.ok(cookieNames.device.startsWith('__Host-'));assert.equal((await digest('fixture')).length,64);assert.equal(await digest('fixture'),await digest('fixture'));});
